/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.idea.completion

import com.galenframework.idea.lang.SpecsLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class SpecsCompletionContributor extends AbstractSpecsCompletionContributor {
	new() {
		this(SpecsLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
