/*
 * generated by Xtext 2.9.0.beta5
 */
package com.galenframework.idea.lang


class SpecFileType extends AbstractSpecFileType {
	public static final SpecFileType INSTANCE = new SpecFileType()
	
	new() {
		super(SpecLanguage.INSTANCE)
	}
}
