/*
 * generated by Xtext 2.9.0
 */
package com.galenframework.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class SpecIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new SpecStandaloneSetupIdea().createInjector
	}

}
