/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.idea.lang


class SpecsFileType extends AbstractSpecsFileType {
	public static final SpecsFileType INSTANCE = new SpecsFileType()
	
	new() {
		super(SpecsLanguage.INSTANCE)
	}
}
