/*
 * generated by Xtext 2.9.2
 */
package com.galenframework


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpecsStandaloneSetup extends SpecsStandaloneSetupGenerated {

	def static void doSetup() {
		new SpecsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
