/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class SpecsWebModule extends AbstractSpecsWebModule {
}
