/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.parser.antlr;

import com.galenframework.parser.antlr.internal.InternalSpecsParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class SpecsTokenSource extends AbstractIndentationTokenSource {

	public SpecsTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		return token.getType() == InternalSpecsParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalSpecsParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		return InternalSpecsParser.RULE_END;
	}

}
