/*
 * generated by Xtext 2.9.0.beta5
 */
package com.galenframework.web

import com.galenframework.SpecRuntimeModule
import com.galenframework.SpecStandaloneSetup
import com.google.inject.Guice
import com.google.inject.Injector
import com.google.inject.Provider
import com.google.inject.util.Modules
import java.util.concurrent.ExecutorService
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor class SpecWebSetup extends SpecStandaloneSetup {
	
	val Provider<ExecutorService> executorServiceProvider;
	
	override Injector createInjector() {
		val runtimeModule = new SpecRuntimeModule()
		val webModule = new SpecWebModule(executorServiceProvider)
		return Guice.createInjector(Modules.override(runtimeModule).with(webModule))
	}
	
}
