/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.tests.components

import com.galenframework.tests.SpecsInjectorProvider
import com.galenframework.specs.Model
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SpecsInjectorProvider)
class ImportTest {

	@Inject
	ParseHelper<Model> parseHelper;

	@Test
	def void shouldImportSingleFile() {
		val result = parseHelper.parse('''
			@import file.gspec
		''')
		Assert.assertNotNull(result)
		Assert.assertNotNull(result.imports)
		val imports = result.imports
		Assert.assertEquals(1, imports.size)
		val importFile = imports.get(0)
		Assert.assertEquals("file.gspec", importFile.fileName)
	}

	@Test
	def void shouldImportMultipleFiles() {
		val result = parseHelper.parse('''
			@import file1.gspec
			@import file2.gspec
		''')
		Assert.assertNotNull(result)
		Assert.assertNotNull(result.imports)
		val imports = result.imports
		Assert.assertEquals(2, imports.size)
		Assert.assertEquals("file1.gspec", imports.get(0).fileName)
		Assert.assertEquals("file2.gspec", imports.get(1).fileName)
	}


}
