/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class SpecsIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new SpecsStandaloneSetupIdea().createInjector
	}

}
