/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class SpecsIdeaModule extends AbstractSpecsIdeaModule {
}
