/*
 * generated by Xtext 2.9.0.beta5
 */
package com.galenframework.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class SpecIdeaModule extends AbstractSpecIdeaModule {
}
