/*
 * generated by Xtext 2.9.0.beta5
 */
package com.galenframework


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpecStandaloneSetup extends SpecStandaloneSetupGenerated {

	def static void doSetup() {
		new SpecStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
