/*
 * generated by Xtext 2.9.0.beta5
 */
package com.galenframework.ui.contentassist

import com.galenframework.ui.contentassist.AbstractSpecProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SpecProposalProvider extends AbstractSpecProposalProvider {
}
