/*
 * generated by Xtext 2.9.0
 */
package com.galenframework.idea.completion

import com.galenframework.idea.lang.SpecLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class SpecCompletionContributor extends AbstractSpecCompletionContributor {
	new() {
		this(SpecLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
