/*
 * generated by Xtext 2.9.2
 */
package com.galenframework.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SpecsProposalProvider extends AbstractSpecsProposalProvider {
}
